### ISSUE TITLE
Cross shard issues

### ISSUE THREAD

**Issue by sandercuppen** [NesCafe62/screeps-pathfinding#1]
Whenever is use the pathfinding modules, and exit a shard (portal, cross shard colonization) i get this error:

Error: Could not find an object with ID 603faa9426a7a1924655b6ce
    at data (:49919:19)
    at Object.get [as spawning] (eval at exports.defineGameObjectProperties (:586:9), :7:68)
    at Object.move (:49995:17)
    at PathingManager.moveCreeps (pathing:519:14)
    at PathingManager.runMoves (pathing:396:10)
    at Director.run (Director:123:10)
    at Object.module.exports.loop (main:20:14)
    at __module (__mainLoop:1:52)
    at __mainLoop:2:3
    at Object.exports.evalCode (:15845:76)

There are no more creeps or structures present in the shard, but the error remains. 
On the shards where i have presence, there are no issues.

I'm not a professional programmer, so please forgive any ignorance.

**Comment by NesCafe62** [comment]
thanks for telling about this issue.

because creep traveled into a portal it disappeared from source shard. there should not be a problem if pathing library will just stop calling move functions for this creep. but according to this error somehow it continued to call creep.move for this absent creep.

possible reasons for that:
1. somehow you stored creep variable between ticks (which is not good. need to get fresh Game.creeps[creepName] every tick) and then called moveTo function for it (or any similar function)
2. cached moves from previous ticks were not cleared properly. if script execution took too long and stopped, but moves were accumulated and in next tick were not cleared. dont know if you use latest version of library, because in last version there is a protection for that case (though I not tested it).

[EDIT]
3. same case as 2 but caused by situation when no creep were moved during the tick. it will try to perform moves stored for previous tick. I think should add a check for that in runMoves and runMovesRoom functions.

ah you say "There are no more creeps or structures present in the shard, but the error remains". most possible it is case 3.
I will add a check for that case.



while this issue is not solved you can wrap line 519 of pathing.js into a try catch, to make others creep movement working. even for ticks when this error occures:
```js
try {
   instance.move(direction);
} catch (error) {
   console.log(`Moving creep ${instance.name} failed`);
   logError(error);
}
```

I will try to reproduce this case sending creep into a portal, and maybe will find something else.

you can add a check before creep.moveTo, to see if Game.creeps[creep.name] is exist:
```js
if (!Game.creeps[creep.name]) {
   console.log(`creep ${creep.name} is not exist on shard ${Game.shard.name}`);
} else if (Game.creeps[creep.name].spawning) {
   console.log(`creep ${creep.name} is still spawning on shard ${Game.shard.name}`);
} else {
   creep.moveTo(target, {/* options... */}); // your moveTo call
}
```

**Comment by NesCafe62** [comment]
you can try to use creep.originalMoveTo instead of moveTo for some cases to see if it also has issues. my library saves original creep moveTo method into originalMoveTo before overriding moveTo prototype method. if error remains it means it's not library's fault

**Comment by NesCafe62** [comment]
I did the test and my creep succesfully teleported to another shard

**Comment by NesCafe62** [comment]
```js
require('pathing');

if (Game.shard.name === 'shard2') {
	function testCreep2(creep) {
		if (!creep || creep.spawning) {
			return;
		}
		const flag = Game.flags['z'];
		if (!flag) {
			return;
		}
		const res = creep.moveTo(flag.pos, {range: 0});
		console.log(res);
	}

	module.exports.loop = function() {
		testCreep2(Game.creeps['test1']);
		Pathing.runMoves();
	};
	return;
}

// ... other code

function testCreep(creep) {
	if (!creep || creep.spawning) {
		return;
	}
	const flag = Game.flags['p'];
	if (!flag) {
		return;
	}
	const res = creep.moveTo(flag.pos, {range: 0});
	console.log(res);
}

module.exports.loop = function() {

	// ... other code

	testCreep(Game.creeps['test1']);

	// ... other code

	Pathing.runMoves();
};
```

created flag "p" at position of a portal

created flag "z" at some position on another shard

then spawned creep manually from console:
```js
Game.spawns['s8.1'].spawnCreep([MOVE, MOVE], 'test1', {memory: {}});
```

creep moved to portal then moved to flag "z" on the other shard

**Comment by NesCafe62** [comment]
notice that I get fresh `Game.creeps[creepName]` for every tick and check if creep exists before calling `moveTo`. I think that might be the reason because error "Could not find an object with ID 603faa9426a7a1924655b6ce" means exactly that. it is generated by screeps backend environment. happends not in your user code. last line from user code was `creep.move` in pathing 519 where creep seems was not a valid object.

**Comment by NesCafe62** [comment]
https://github.com/NesCafe62/screeps-pathfinding/commit/d55bc9bc3cb72120664d56b218a54d83aac92a4f hopefully this commit should fix it

**Comment by sandercuppen** [comment]
Thanks for the explanation. I integrated the latest version of your code and the problem is fixed now.
