### ISSUE TITLE
Explanation of fixPath option

### ISSUE THREAD

**Issue by SystemParadox** [NesCafe62/screeps-pathfinding#4]
Hi, sorry for the question but I'm struggling to understand the purpose of the fixPath option. I think it's something to do with the heuristicWeight, but I haven't been able to figure out how this can happen with the default weight of 1.2, so unless you're cranking the weight up really high I'm not sure what case this is trying to fix.

Can anyone provide any further insight?

**Comment by NesCafe62** [comment]
sure

![изображение](https://github.com/NesCafe62/screeps-pathfinding/assets/1944556/544570c2-245b-4507-b7c2-b80d74ad072d)

with default heuristic 1.2 sometimes screeps pathfinder produce this result when roads use pathing cost of 1.
so instead of changing heuristic to 1 and have heavier calculations I decide to implement quick single-pass over result array of positions and "fix" path for those cases

**Comment by SystemParadox** [comment]
Ah thanks I see it now. The off-road tile has `g(n)` increased by 1 because it's a plain instead of a road, but if it's 1 tile closer to the goal then the heuristicWeight means `h(n)` is decreased by 1.2, so it favours the off-road tile.

For example if the target is 12 tiles directly north of the corner:

On-road path: `g(n) = 5`, `h(n) = 1.2 * 12`, `f(n) = 19.4`
Off-road path: `g(n) = 6`, `h(n) = 1.2 * 11`, `f(n) = 19.2`

So this is actually quite likely to happen!

**Comment by NesCafe62** [comment]
yep. cool that you could understand why it happens in more details and share that info
